### ISSUE TITLE
Multiple zones error

### ISSUE THREAD

**Issue by Kev1000000** [thevoltagesource/LennoxiComfort#12]
It appears that if there is any error with communicating with myicomfort, the zones get messed up and all zones report what zone 0 states are.  This makes using this component quite unreliable for multizone systems.

Is there any chance this can be addressed?

**Comment by thevoltagesource** [comment]
I looked thru the code this morning and I think I found the issue.  The problem is in the back end API, with how I reuse code between testing connections with the initial status pull and subsequent status pulls. Since I only have a single system with a single zone, I figured I would eventually run into a problem related to having multiples.  I will get this fixed soon.

**Comment by Kev1000000** [comment]
You're a champion.  Happy to test any changes as well, or even give you my account creds if you need a testing environment.

**Comment by thevoltagesource** [comment]
OK, I fixed the code so that my zone fall back only happens on initial system connection testing as I originally intended.  To test you will need to edit the manifest.json file in the custom_components/myicomfort folder and update the required version of myicomfort to 0.3.1.
`"requirements": ["voluptuous", "myicomfort==0.3.1"]`
Once that is changed, restart Home Assistant and it will install the new API version.   I tested the update against my system and everything is working. Let me know if it functions as expected for you and I will update the manifest in the repository so everyone can pick it up.

**Comment by Kev1000000** [comment]
Updated to 0.3.1.  So far so good!  Though, it usually is good until there is an error with myicomfort, so I will report back in terms of its stability to see if it is truly resolved.  Thanks for the quick turn around on this, it is much appreciated!

**Comment by Kev1000000** [comment]
Been rock solid for over 24 hours now.  I'd be comfortable calling this issue resolved.  Thanks again!
