### ISSUE TITLE
Many commands seem to not "stick"

### ISSUE THREAD

**Issue by Kev1000000** [thevoltagesource/LennoxiComfort#13]
I have quite a few rules in Node Red that adjust the thermostat automatically, but many times these rules don't actually change the thermostat setpoint.  Home Assistant thinks the setpoint was changed, but after a refresh of the data, the setpoint goes back to what it was previously.  This also occurs with manual adjustment via HA itself.

I am not sure if the commands ever make it to Lennox or not, or something else is awry, but it's quite difficult to live with since it is seemingly random.  Would it be possible to adjust the thermostat back to the original setting if a request fails?  Or log it somehow so we can try to get to the bottom of it?

I know Lennox's servers aren't the most reliable, but if we can determine it's a failure on their side, I wonder if a modest retry strategy would make sense.

**Comment by thevoltagesource** [comment]
My thermostat settings are currently very static so I don't see this often, but I do occasionally notice that after getting home the thermostat is still in away mode.  I check the HA log book and the command fired to take the thermostat out of away mode but it didn't happen.  Whether this was a failed connection to the cloud for that request, or a failed connection on the part of the thermostat checking in, I haven't dug that deep to determine.  I have considered creating an entity that holds expected states for certain objects and an automation that runs ever 10 minutes adjusting items that are not as expected for what ever reason. This would make up for cloud failure or a child messing with things. 

To your logging question, the API behind the integration will raise an ERROR level message stating 'Thermostat cloud service not responding.' whenever it fails to make a successful connection to the cloud service wether querying status or pushing data to it. It will also raise INFO level messages on start up 'Connecting to Lennox MyiComfort'. If you have Home assistant's logger enabled with the appropriate logging level these messages will show up in the log. 

The integration and supporting API are passive and only do things on demand.  By default Home Assistant polls climate devices every 60 seconds and will update the climate entity on each poll. This means that if you (or an automation) changed the fan mode and the update did not make it to the cloud, the fan mode in HA will revert back to the cloud's setting on the next successful poll. Since HA not reaching the cloud also means the thermostat can't reach the cloud either and I'm not sure which setting (tstat or cloud) wins on first connect after a loss of connectivity. Regardless, HA will update the climate entity within 60 seconds. You can set a custom polling interval by adding scan_interval to your climate configuration.

```
climate:
  - platform: myicomfort
    username: !secret icomfort_username
    password: !secret icomfort_password
    scan_interval: 30
```

I wouldn't recommend setting this below 60 long term as you don't want Lennox to block your IP for excessive connections.

All of that to say, the issue as far as I can tell is the poor reliability of the Lennox cloud service.  I have in the back of my mind a desire to try and write a fake cloud service that would run locally and would intercept the calls from the tstat, eliminating the cloud dependency, but my programming is around hobbyist level and that task seems a bit daunting.

Hopefully I understood this question "Would it be possible to adjust the thermostat back to the original setting if a request fails?" correctly and actually answered it in the info above.   If I missed the mark, can you will ask it a different way?  I will be happy to try again. I am also open to ideas on how to troubleshoot this and am willing to try and make this integration reliable in spite of Lennox. :)

**Comment by Kev1000000** [comment]
Thanks so much for the info here!  I can help fill in some details to help narrow things down.  I have noticed when using their official Android app that when the commands seem to revert, it's almost always when the Android app is showing the "servers are down" message, so I am pretty confident the issue is with Lennox's servers being crap.

In terms of the state entity, is that something you could do in the API logic itself?  Instead of creating entities within HA, you could add "queuedSetpoint" or something that holds the last changed setpoint within HA's climate entity, and then if the poll of Lennox's API comes back that doesn't match with that queued variable, you'd resend within the API.  Maybe have a max retry of 10 attempts, and after 10, just set the queued variable to whatever is coming back from Lennox.

Thoughts?

**Comment by thevoltagesource** [comment]
I was giving this more thought this morning after I woke up to a very cold house.  Apparently the request to exit away mode didn't make it to the cloud when I got home last night. 

Unfortunately my code isn't 'running' and doesn't have a loop to track cloud response or do things on its own. It is just a library that HA imports and executes methods from.  Home Assistant at its core is a state engine and reacts to states and changes so we will need to find a way to make it work for us.

I am posing this problem to the HA community so we can get a wider audience and significantly more brain power working on ideas. [Here is the post.](https://community.home-assistant.io/t/handling-temporary-cloud-service-interruptions/168006)

**Comment by Kev1000000** [comment]
Ah, sorry to hear you're experiencing the same issues.  It's really unfortunate when it happens, and for me at least, it happens quite often.  Probably once per day.

Thanks for reaching out to the HA folks.  Hopefully they can help us think of a solution.  I'd be happy to jump in on that thread if it begins to go in a direction of just "get a local stat."  Not sure about your setup, but I have no choice but to stick with this Lennox stat with my AC/Furnace unit.  So a local communicating stat is no option.

I am sure I could whip up some NodeRed logic to essentially build in a retry engine, but that seems like a ton of overhead and might cause some other downstream issues if the outages last longer than a few minutes.

Let's hope the HA community can help us here!  And thank you for dedication to this library and trying to make the Lennox integration into HA rock solid.

**Comment by Wat3rh3ad** [comment]
First off I want to thank all who participated in this project. I'm posting this to make the developers aware of what I have been experiencing.
 
The problem I am having is when going from cooling to heat, the desired temp set in the thermostat will stay there for maybe 20 to 30 seconds and then the desired temp will all of the sudden change to 67 degrees. Even if I change the desired again it will wait again and revert back to 67. I don't have this problem at all on the cooling side of the thermostat. 

Thank you to the developers who put their time and effort into this awesome project.  Glad to be able to get this working through HA!   Thanks!!!

**Comment by thevoltagesource** [comment]
Hi @Wat3rh3ad - Does this only happen after switching modes? Since this integration polls the cloud service and the thermostat poles the cloud server, trying to do too many things at the same time can end up with your requests getting overwritten by the thermostat updating its state to the cloud when the mode changes. There are also times when the cloud just isn't accepting updates so the request to change is sent to the cloud but when the integration reads the cloud status the original settings are returned.

**Comment by thevoltagesource** [comment]
From everything I have read and seen, this is the issue of relying on a cloud service which may or may not be online.  This is not something I can address in the code.  HA doesn't have a framework for resolving this.  I am closing this issue.
