### ISSUE TITLE
HA Status do not update when connected to Alexa

### ISSUE THREAD

**Issue by klingon888** [thevoltagesource/LennoxiComfort#22]
When I expose climate.icomfort to Alexa, the component's State attribute "hvac_action" in HA stops updating and shows "Idle" even when my HVAC is running. The component's history shows the following. Once I remove climate.icomfort from being exposed to Alexa, the State attribute will show the correct status of "heating".

![image](https://user-images.githubusercontent.com/30375535/109391461-411a0400-78e5-11eb-98e4-885c2af644cf.png)

**Comment by thevoltagesource** [comment]
What version of HA are you running?  Alexa should not impact the state of a different integration but things happen.  I use the HA standard variables for hvac_action to improve compatibility with Alexa/Google. Since I don't have an echo device, I'm not familiar with how the Alexa integration works or impacts HA.  Have you brought this up in the HA community forum?

**Comment by thevoltagesource** [comment]
Hey @klingon888 I am going to close this as this seems to be an issue with the Alexa integration working with clients and not the Lennox integration specifically.  I would suggest bringing this up in the community forums.  I will be happy to add to that discussion if there is a question specific to this integration.
