### ISSUE TITLE
No Entity Created

### ISSUE THREAD

**Issue by markqcheese** [thevoltagesource/LennoxiComfort#33]
I followed the directions, installed the repository, made the entry in configuration.yaml and no entity is being created. I have a Lennoc icomfort M30 thermostat. I can control it from the Lennox mobile app or the Lennox web page. 

Help?

**Comment by thevoltagesource** [comment]
Hi @markqcheese, this integration only supports the Lennox WiFi thermostat that link to myicomfort.com.  It doesn't support the x30 series that use lennoxicomfort.com site.  PeteRanger is developing an integration for the [S30 ](https://github.com/PeteRager/lennoxs30) which should work with the M30 since they talk to the same cloud service.

**Comment by markqcheese** [comment]
That makes more Sense. Thanks!!!
