### ISSUE TITLE
Error while setting up platform myicomfort

### ISSUE THREAD

**Issue by noisyscott** [thevoltagesource/LennoxiComfort#5]
Got through a configuration error, but am now getting an error thrown from inside climate.py

(this is from a hassio 0.93.2 installation)

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
>     SLOW_SETUP_MAX_WAIT, loop=hass.loop)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/myicomfort/climate.py", line 109, in setup_platform
>     from myicomfort.api import Tstat
> ModuleNotFoundError: No module named 'myicomfort'

**Comment by thevoltagesource** [comment]
I am running Home Assistant instead of Hassio so I can't recreate your exact setup.  The error comes from the python myicomfort api not being available.  I just upgraded to 0.93.2 and then uninstalled the api package.  When I restarted HA, the component loaded and I see this in the log:

> [homeassistant.util.package] Attempting install of myicomfort==0.2.1
> [homeassistant.components.climate] Setting up climate.myicomfort
> [myicomfort.api] Initializing Thermostat

Can you try manually installing the python package in the Hassio python environment?
`python3 -m pip install myicomfort==0.2.1`

**Comment by thevoltagesource** [comment]
Haven't heard back so I will close this issue.  I will be posting an update for 0.96 soon.
