### ISSUE TITLE
Broken with 0.96 upgrade

### ISSUE THREAD

**Issue by manonstreet** [thevoltagesource/LennoxiComfort#7]
My climate entity is no longer available.

As per the blog, there was a major refactoring of the climate code.  Presumably something in there caused the breakage:
[https://www.home-assistant.io/blog/2019/07/17/release-96/#climate](url)

**Comment by jmesberg** [comment]
Same here. Hopefully creator is still working on this and will update soon.

**Comment by thevoltagesource** [comment]
I am still here.  I will try and get this working this weekend.

**Comment by jmesberg** [comment]
Thank you!

**Comment by thevoltagesource** [comment]
Getting it working was easier than I thought. It helped to stand up the latest version in Docker instead of trying to bring my house up to 0.96 first.

There are some things to clean up but we are back to a working state.  I have some other changes to implement so I might run in to some core things to fix along the way.  Let me know if this is working for you.

**Comment by putz612** [comment]
Just tried the latest patch with 0.96.2 and it seems to work perfectly.

**Comment by jmesberg** [comment]
same here, all working well again. Thank you for your very prompt action on this.
